name: code_my_screen
description: "Show me the cooooode"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.2

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.3.0
  stop_watch_timer: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/screenshots/
